# -*- coding: utf-8 -*-
"""predict_meta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15jqDWszSnReGfG3uvNjLEXXnCjiwMhEz
"""

"""
predict_meta_ensemble.py
Инференс мета-модели (stacking BERT + LightGBM) на новых данных.

Этот скрипт загружает обученную мета-модель и применяет её к вероятностям
базовых моделей (BERT и LightGBM) на тестовой выборке.

Предварительно должны быть получены:
  - test_bert_probs.npy — вероятности BERT на тесте
  - test_lgb_probs.npy (или .csv с колонкой target) — вероятности LightGBM на тесте
  - meta_lgb_model.txt — обученная мета-модель

"""
import os
import argparse
import numpy as np
import pandas as pd
import lightgbm as lgb

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Apply stacking meta-model to BERT + LightGBM predictions"
    )

    # --- Мета-модель ---
    p.add_argument(
        "--meta-model-path", type=str, required=True,
        help="Путь к обученной мета-модели (meta_lgb_model.txt)",
    )

    # --- Вероятности базовых моделей на тесте ---
    p.add_argument(
        "--bert-test-probs", type=str, required=True,
        help="Путь к .npy с вероятностями BERT на тесте",
    )
    p.add_argument(
        "--lgb-test-probs", type=str, required=True,
        help="Путь к .npy (или .csv с колонкой target) с вероятностями LightGBM на тесте",
    )

    # --- Тестовые данные ---
    p.add_argument(
        "--test-csv", type=str, required=True,
        help="Тестовый CSV для submission (должен иметь колонку row_id / Unnamed: 0 / индекс)",
    )
    p.add_argument(
        "--output-path", type=str, default="submission_meta_ensemble.csv",
        help="Куда сохранять финальный submission.csv",
    )

    return p.parse_args()


ARGS = parse_args()

def load_probs(path: str, expected_len: int, name: str) -> np.ndarray:
    """
    Универсальный загрузчик вероятностей:
      - .npy  -> np.load
      - .csv  -> колонка 'target'
    Проверяет длину, чтобы избежать тихого рассинхрона.
    """
    ext = os.path.splitext(path)[1].lower()
    if ext == ".npy":
        arr = np.load(path).astype(np.float32).ravel()
    elif ext == ".csv":
        df = pd.read_csv(path)
        if "target" not in df.columns:
            raise ValueError(f"В {path} нет колонки 'target'")
        arr = df["target"].to_numpy(dtype=np.float32)
    else:
        raise ValueError(f"Неизвестный формат {path}, ожидался .npy или .csv")

    if len(arr) != expected_len:
        raise ValueError(
            f"{name}: длина {len(arr)} не совпадает с ожидаемой {expected_len}. "
            f"Проверьте, что все файлы построены на одном и том же наборе строк."
        )
    return arr

META_FEATURE_NAMES = ["bert_prob", "lgb_prob", "bert_x_lgb", "abs_diff"]


def build_meta_features(bert_p: np.ndarray, lgb_p: np.ndarray) -> pd.DataFrame:
    """
    Четыре признака на выходе базовых моделей:
      - p_bert, p_lgb
      - их произведение (согласованность)
      - модуль разности (уверенность/неуверенность)

    Возвращает DataFrame с именами колонок, чтобы избежать warning от sklearn.
    """
    return pd.DataFrame({
        "bert_prob": bert_p,
        "lgb_prob": lgb_p,
        "bert_x_lgb": bert_p * lgb_p,
        "abs_diff": np.abs(bert_p - lgb_p),
    })

def main() -> None:
    # --- 1. Загружаем мета-модель ---
    print(f"[load] мета-модель: {ARGS.meta_model_path}")
    if not os.path.exists(ARGS.meta_model_path):
        raise FileNotFoundError(f"Мета-модель не найдена: {ARGS.meta_model_path}")

    meta_booster = lgb.Booster(model_file=ARGS.meta_model_path)

    # --- 2. Загружаем тестовые данные ---
    test_df = pd.read_csv(ARGS.test_csv)
    n_test = len(test_df)
    print(f"[data] test: {n_test} строк")

    # --- 3. Загружаем вероятности базовых моделей ---
    bert_test = load_probs(ARGS.bert_test_probs, n_test, "bert-test")
    lgb_test = load_probs(ARGS.lgb_test_probs, n_test, "lgb-test")

    print(f"[probs] BERT: min={bert_test.min():.4f}, max={bert_test.max():.4f}, mean={bert_test.mean():.4f}")
    print(f"[probs] LGB:  min={lgb_test.min():.4f}, max={lgb_test.max():.4f}, mean={lgb_test.mean():.4f}")
    print(f"[probs] corr(BERT, LGB) = {np.corrcoef(bert_test, lgb_test)[0, 1]:.3f}")

    # --- 4. Строим мета-фичи ---
    X_test_meta = build_meta_features(bert_test, lgb_test)

    # --- 5. Предсказываем через мета-модель ---
    # Booster.predict возвращает вероятности для класса 1
    final_probs = meta_booster.predict(X_test_meta.values)

    print(f"[pred] final probs: min={final_probs.min():.4f}, max={final_probs.max():.4f}, mean={final_probs.mean():.4f}")

    # --- 6. Формируем submission ---
    if "row_id" in test_df.columns:
        row_id = test_df["row_id"]
    elif "Unnamed: 0" in test_df.columns:
        row_id = test_df["Unnamed: 0"]
    else:
        row_id = np.arange(n_test)

    submission = pd.DataFrame({"row_id": row_id, "target": final_probs})

    # Создаём директорию для output, если её нет
    output_dir = os.path.dirname(ARGS.output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    submission.to_csv(ARGS.output_path, index=False)

    print("\n[done] Submission preview:")
    print(submission.head())
    print(f"[done] submission saved: {ARGS.output_path}")


if __name__ == "__main__":
    main()
