# -*- coding: utf-8 -*-
"""predict_lightgbm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Fe3wQ4Z_osXaIod4c2edXqGySC-jGXq
"""

"""
predict_lightgbm.py
Инференс 8-fold LightGBM (обученного через train_lightgbm.py)
на новых данных.

Для каждого объекта:
  1) считаются табличные фичи + hotel-статистики (на всём train),
  2) считается LaBSE-эмбеддинг,
  3) применяются все 8 моделей-фолдов,
  4) предсказания усредняются.

Предварительно должны быть получены через train_lightgbm.py:
  - models/lightgbm_labse/lgb_fold_*.txt  (8 файлов)
  - models/lightgbm_labse/train_config.json (для восстановления путей/параметров)

"""
# CONFIG / CLI

import os
import re
import glob
import argparse

import numpy as np
import pandas as pd
import lightgbm as lgb
from sentence_transformers import SentenceTransformer


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Apply 8-fold LightGBM (with LaBSE + tabular features) to new data"
    )

    # Пути
    # ЗАМЕНИТЕ на свои пути
    p.add_argument(
        "--train-path", type=str, required=True,
        help="Полный train-CSV (нужен для расчёта hotel-статистик)",
    )
    p.add_argument(
        "--test-path", type=str, required=True,
        help="Тестовый CSV для сабмита (колонки: hotel_id, supplier_room_name, [row_id])",
    )
    p.add_argument(
        "--models-dir", type=str, required=True,
        help="Директория с обученными моделями (lgb_fold_*.txt) и train_config.json",
    )
    p.add_argument(
        "--output-path", type=str, default="submission_lgb.csv",
        help="Куда сохранять финальный submission.csv",
    )

    # Имена колонок
    p.add_argument("--text-col", type=str, default="supplier_room_name")
    p.add_argument("--target-col", type=str, default="target")

    # Сплит (должен совпадать с train)
    p.add_argument("--test-size", type=float, default=0.15)
    p.add_argument("--n-folds", type=int, default=8)
    p.add_argument("--seed", type=int, default=42)

    # LaBSE
    p.add_argument("--embedding-model", type=str, default="sentence-transformers/LaBSE")
    p.add_argument("--embedding-batch-size", type=int, default=256)
    p.add_argument("--embedding-device", type=str, default=None)

    return p.parse_args()


ARGS = parse_args()

TEXT_COL = ARGS.text_col
TARGET_COL = ARGS.target_col
SEED = ARGS.seed

# TEXT PREPROCESSING

def preprocess_text(text):
    """Та же чистка, что и при обучении."""
    if not isinstance(text, str) or text.strip() == "":
        return None
    original = text.strip()
    if re.fullmatch(r"[\d\s\W]+", original):
        return None
    text = original.lower()
    text = re.sub(r"[^a-zа-яё0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    if len(text.split()) < 2:
        return None
    return text

# FEATURE ENGINEERING

EURO_MARKERS = {
    "de": r"\b(doppelzimmer|einzelzimmer|zimmer|familienzimmer|suite|mit)\b",
    "fr": r"\b(chambre|singuliere|vue|avec|lit|familiale|superieure)\b",
    "it": r"\b(camera|matrimoniale|singola|doppia|vista|con|letto|superiore)\b",
    "es": r"\b(habitacion|doble|individual|con|vista|cama|superior)\b",
}


def has_foreign_language(text: str) -> int:
    if not isinstance(text, str) or text.strip() == "":
        return 0
    t = text.lower()
    for pattern in EURO_MARKERS.values():
        if re.search(pattern, t):
            return 1
    return 0


def add_features(df: pd.DataFrame) -> pd.DataFrame:
    """Та же генерация табличных фич, что и при обучении."""
    df_ = df.copy()
    text = df_["text_clean"].fillna("")
    orig = df_[TEXT_COL].fillna("")

    df_["text_length"] = orig.apply(len)
    df_["word_count"] = text.apply(lambda x: len(x.split()))
    df_["unique_ratio"] = text.apply(
        lambda x: len(set(x.split())) / max(len(x.split()), 1)
    )
    df_["upper_ratio"] = orig.apply(
        lambda x: sum(1 for c in x if c.isupper()) / max(len(x), 1)
    )
    df_["has_parentheses"] = orig.apply(lambda x: int("(" in x))
    df_["digit_count"] = orig.apply(lambda x: sum(1 for c in x if c.isdigit()))

    df_["ru_ratio"] = text.apply(
        lambda x: sum(1 for c in x if "а" <= c <= "я" or c == "ё") / max(len(x), 1)
    )
    df_["en_ratio"] = text.apply(
        lambda x: sum(1 for c in x if "a" <= c <= "z") / max(len(x), 1)
    )
    df_["has_foreign_lang"] = orig.apply(has_foreign_language)

    bed_configs = [
        "king", "queen", "twin", "double", "single", "bunk",
        "двуспальн", "односпальн", "1 bed", "2 bed",
        "1 кровать", "2 кровати", "2 отдельные",
    ]
    df_["has_bed_config"] = text.apply(
        lambda x: int(any(b in x for b in bed_configs))
    )

    room_levels = [
        "standard", "стандарт", "deluxe", "делюкс",
        "superior", "executive", "premium", "премиум",
        "classic", "comfort", "комфорт", "люкс", "economy",
    ]
    df_["has_room_level"] = text.apply(
        lambda x: int(any(r in x for r in room_levels))
    )

    view_words = [
        "sea view", "ocean view", "вид на море",
        "city view", "вид на город", "garden view",
        "pool view", "mountain view", " view", " вид",
    ]
    df_["has_view"] = text.apply(lambda x: int(any(v in x for v in view_words)))

    balcony_words = ["balcon", "terrace", "террас", "балкон", "лоджия"]
    df_["has_balcony"] = text.apply(
        lambda x: int(any(b in x for b in balcony_words))
    )

    family_words = ["family", "семейн", "child", "детск", "kids"]
    df_["is_family"] = text.apply(lambda x: int(any(f in x for f in family_words)))

    biz = [
        "has_bed_config", "has_room_level", "has_view",
        "has_balcony", "is_family",
    ]
    df_["business_completeness"] = df_[biz].sum(axis=1) / len(biz)
    return df_


TABULAR_FEATURE_COLS = [
    "text_length", "word_count", "unique_ratio", "upper_ratio",
    "has_parentheses", "digit_count", "ru_ratio", "en_ratio",
    "has_foreign_lang",
    "has_bed_config", "has_room_level", "has_view",
    "has_balcony", "is_family", "business_completeness",
    "hotel_positive_rate", "hotel_room_count", "hotel_target_std",
]

# HOTEL STATS

def compute_hotel_stats(df_train: pd.DataFrame):
    """
    Для инференса hotel-статистики считаются на ВСЁМ train
    (с тем же сплитом, что был при обучении — 85% train_val).
    Это нужно, чтобы для теста были честные фичи без лика.
    """
    hotel_stats = df_train.groupby("hotel_id")[TARGET_COL].agg(
        hotel_positive_rate="mean",
        hotel_room_count="count",
        hotel_target_std="std",
    ).reset_index()
    hotel_stats["hotel_target_std"] = hotel_stats["hotel_target_std"].fillna(0)
    global_mean = df_train[TARGET_COL].mean()
    return hotel_stats, global_mean


def add_hotel_features(
    df_target: pd.DataFrame,
    hotel_stats: pd.DataFrame,
    global_mean: float,
) -> pd.DataFrame:
    df_target = df_target.merge(hotel_stats, on="hotel_id", how="left")
    df_target["hotel_positive_rate"] = df_target["hotel_positive_rate"].fillna(global_mean)
    df_target["hotel_room_count"] = df_target["hotel_room_count"].fillna(0)
    df_target["hotel_target_std"] = df_target["hotel_target_std"].fillna(0)
    return df_target

# EMBEDDINGS

def build_embeddings(texts, model_name: str, batch_size: int, device):
    print(f"Загружаем эмбеддинг-модель {model_name} (device={device or 'auto'})...")
    model = SentenceTransformer(model_name, device=device)
    embeddings = model.encode(
        list(texts),
        batch_size=batch_size,
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=True,
    )
    return embeddings.astype(np.float32)

# MAIN

def main() -> None:
    # 1. Загружаем реальный тест
    real_test = pd.read_csv(ARGS.test_path)
    print("Реальный тест:", real_test.shape)

    if "row_id" in real_test.columns:
        row_id = real_test["row_id"]
    elif "Unnamed: 0" in real_test.columns:
        row_id = real_test["Unnamed: 0"]
    else:
        row_id = real_test.index

    # 2. Чистим текст теста
    real_test["text_clean"] = real_test[TEXT_COL].apply(preprocess_text)
    real_test["text_clean"] = real_test["text_clean"].fillna("")

    # 3. Восстанавливаем train_val (тот же сплит, что при обучении)
    df_full = pd.read_csv(ARGS.train_path)
    from sklearn.model_selection import train_test_split
    df_train_val_recon, _ = train_test_split(
        df_full, test_size=ARGS.test_size, random_state=SEED, stratify=df_full[TARGET_COL]
    )
    df_train_val_recon["text_clean"] = df_train_val_recon[TEXT_COL].apply(preprocess_text)
    df_train_val_recon = df_train_val_recon.dropna(subset=["text_clean"]).reset_index(drop=True)
    df_train_val_recon = df_train_val_recon.drop_duplicates(
        subset=["hotel_id", TEXT_COL, TARGET_COL]
    ).reset_index(drop=True)
    print(f"train_val для hotel-stats: {len(df_train_val_recon)} строк")

    # 4. Считаем hotel-статистики на всём train_val
    real_test["hotel_id"] = real_test["hotel_id"].astype(str)
    hotel_stats_full, global_mean_full = compute_hotel_stats(df_train_val_recon)
    hotel_stats_full["hotel_id"] = hotel_stats_full["hotel_id"].astype(str)

    real_test = add_hotel_features(real_test, hotel_stats_full, global_mean_full)
    real_test = add_features(real_test)

    X_real_tab = real_test[TABULAR_FEATURE_COLS].fillna(0).values

    # 5. LaBSE-эмбеддинги для теста
    real_embeddings = build_embeddings(
        real_test["text_clean"].tolist(),
        ARGS.embedding_model, ARGS.embedding_batch_size, ARGS.embedding_device,
    )
    X_real = np.hstack([X_real_tab, real_embeddings])

    # 6. Загружаем все 8 моделей-фолдов и предсказываем
    fold_model_paths = sorted(glob.glob(os.path.join(ARGS.models_dir, "lgb_fold_*.txt")))
    print(f"Найдено моделей: {len(fold_model_paths)} (ожидалось {ARGS.n_folds})")
    assert len(fold_model_paths) == ARGS.n_folds, (
        f"Не все фолды найдены — проверьте {ARGS.models_dir}"
    )

    real_preds = np.zeros((len(fold_model_paths), len(real_test)), dtype=np.float32)
    for i, path in enumerate(fold_model_paths):
        booster = lgb.Booster(model_file=path)
        real_preds[i] = booster.predict(X_real)
        print(f"  fold {i}: preds mean={real_preds[i].mean():.4f}")

    final_probs = real_preds.mean(axis=0)
    print(f"\nФинальные предсказания: mean={final_probs.mean():.4f}, "
          f"min={final_probs.min():.4f}, max={final_probs.max():.4f}")

    # 7. Сохраняем submission
    output_dir = os.path.dirname(ARGS.output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    final_submission = pd.DataFrame({"row_id": row_id, "target": final_probs})
    final_submission.to_csv(ARGS.output_path, index=False)

    print(f"\n Финальный submission: {ARGS.output_path}")
    print(f"Размер: {final_submission.shape}")
    print(final_submission.head())