# -*- coding: utf-8 -*-
"""Meta model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uzlEFeHsComPNmuecL6O7cqo8TF8IApt
"""

"""
train_meta_ensemble.py
Обучение мета-модели (stacking) поверх двух базовых моделей:
  - DistilBERT (multilingual) — вероятности по тексту номера отеля
  - LightGBM на табличных фичах + LaBSE-эмбеддингах

Мета-модель — лёгкий LightGBM-классификатор, обученный на
предсказаниях базовых моделей (и их комбинациях).
Логика соответствует ноутбуку bert-lgb.ipynb.

Как пользоваться:
  1. Сначала должны быть обучены базовые модели (BERT и LGB) и
     сохранены их вероятности на holdout-выборке и на тесте.
  2. Запустить этот скрипт, указав пути к артефактам.
  3. На выходе: мета-модель (.txt), submission.csv и метрики на holdout.

"""

import os
import json
import random
import argparse
from typing import Tuple

import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import average_precision_score, roc_auc_score

# CLI / CONFIG

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Train stacking meta-model over BERT + LightGBM predictions"
    )

    # Пути к артефактам базовых моделей
    # ЗАМЕНИТЕ на свои пути. Формат: .npy (массив float32/float64 длиной N)
    p.add_argument(
        "--bert-holdout-probs", type=str, required=True,
        help="Путь к .npy с вероятностями BERT на holdout-выборке",
    )
    p.add_argument(
        "--bert-test-probs", type=str, required=True,
        help="Путь к .npy с вероятностями BERT на тесте",
    )
    p.add_argument(
        "--lgb-holdout-probs", type=str, required=True,
        help="Путь к .npy с вероятностями LightGBM на holdout-выборке",
    )
    p.add_argument(
        "--lgb-test-probs", type=str, required=True,
        help=(
            "Путь к .npy (или .csv с колонкой target) "
            "с вероятностями LightGBM на тесте"
        ),
    )

    # Данные
    p.add_argument(
        "--holdout-csv", type=str, required=True,
        help="CSV с holdout-выборкой (должен содержать таргет и иметь ту же длину, что и holdout_probs)",
    )
    p.add_argument(
        "--test-csv", type=str, required=True,
        help="Тестовый CSV для submission (должен иметь колонку row_id / Unnamed: 0 / индекс)",
    )
    p.add_argument("--target-col", type=str, default="target", help="Имя колонки с таргетом")

    # Выходы
    p.add_argument(
        "--output-dir", type=str, default="models/meta_ensemble",
        help="Куда сохранять мета-модель, submission и конфиг",
    )

    # Гиперпараметры мета-модели
    p.add_argument("--n-estimators", type=int, default=300)
    p.add_argument("--learning-rate", type=float, default=0.03)
    p.add_argument("--num-leaves", type=int, default=7)
    p.add_argument("--min-child-samples", type=int, default=10)
    p.add_argument("--reg-lambda", type=float, default=2.0)
    p.add_argument("--n-splits", type=int, default=5, help="Число фолдов для честной OOF-оценки")
    p.add_argument("--seed", type=int, default=42)

    return p.parse_args()


ARGS = parse_args()

# REPRODUCIBILITY

def seed_everything(seed: int = 42) -> None:
    random.seed(seed)
    np.random.seed(seed)


seed_everything(ARGS.seed)

# IO HELPERS

def load_probs(path: str, expected_len: int, name: str) -> np.ndarray:
    """
    Универсальный загрузчик вероятностей:
      - .npy  -> np.load
      - .csv  -> колонка 'target'
    Проверяет длину, чтобы избежать тихого рассинхрона.
    """
    ext = os.path.splitext(path)[1].lower()
    if ext == ".npy":
        arr = np.load(path).astype(np.float32).ravel()
    elif ext == ".csv":
        df = pd.read_csv(path)
        if "target" not in df.columns:
            raise ValueError(f"В {path} нет колонки 'target'")
        arr = df["target"].to_numpy(dtype=np.float32)
    else:
        raise ValueError(f"Неизвестный формат {path}, ожидался .npy или .csv")

    if len(arr) != expected_len:
        raise ValueError(
            f"{name}: длина {len(arr)} не совпадает с ожидаемой {expected_len}. "
            f"Проверьте, что все файлы построены на одном и том же наборе строк."
        )
    return arr

# META-FEATURES

META_FEATURE_NAMES = ["bert_prob", "lgb_prob", "bert_x_lgb", "abs_diff"]


def build_meta_features(bert_p: np.ndarray, lgb_p: np.ndarray) -> np.ndarray:
    """
    Четыре признака на выходе базовых моделей:
      - p_bert, p_lgb
      - их произведение (согласованность)
      - модуль разности (уверенность/неуверенность)
    """
    return np.column_stack([
        bert_p,
        lgb_p,
        bert_p * lgb_p,
        np.abs(bert_p - lgb_p),
    ])

# META-MODEL

def make_meta_lgb(seed: int) -> lgb.LGBMClassifier:
    return lgb.LGBMClassifier(
        n_estimators=ARGS.n_estimators,
        learning_rate=ARGS.learning_rate,
        num_leaves=ARGS.num_leaves,
        min_child_samples=ARGS.min_child_samples,
        reg_lambda=ARGS.reg_lambda,
        objective="binary",
        random_state=seed,
        n_jobs=-1,
        verbose=-1,
    )


def train_meta_model(
    X_meta: np.ndarray, y_meta: np.ndarray
) -> Tuple[lgb.LGBMClassifier, np.ndarray]:
    """
    1) Честная OOF-оценка качества мета-модели (StratifiedKFold).
    2) Финальное обучение на всех holdout-данных.
    Возвращает (финальная модель, OOF-предсказания).
    """
    skf = StratifiedKFold(n_splits=ARGS.n_splits, shuffle=True, random_state=ARGS.seed)
    meta_oof = np.zeros(len(X_meta), dtype=np.float32)

    for fold, (tr_idx, val_idx) in enumerate(skf.split(X_meta, y_meta), start=1):
        m = make_meta_lgb(seed=ARGS.seed + fold)
        m.fit(X_meta[tr_idx], y_meta[tr_idx])
        meta_oof[val_idx] = m.predict_proba(X_meta[val_idx])[:, 1]

    pr_auc = average_precision_score(y_meta, meta_oof)
    roc_auc = roc_auc_score(y_meta, meta_oof)
    print(f"[meta] OOF PR-AUC = {pr_auc:.4f} | ROC-AUC = {roc_auc:.4f}")

    # Baseline — простое среднее базовых моделей
    # (нужны исходные вероятности — восстановим из X_meta)
    simple_avg = (X_meta[:, 0] + X_meta[:, 1]) / 2.0
    pr_auc_avg = average_precision_score(y_meta, simple_avg)
    print(f"[meta] простое среднее BERT+LGB: PR-AUC = {pr_auc_avg:.4f}")

    # Финальная модель — на всём holdout
    final_model = make_meta_lgb(seed=ARGS.seed)
    final_model.fit(X_meta, y_meta)
    return final_model, meta_oof

# MAIN

def main() -> None:
    os.makedirs(ARGS.output_dir, exist_ok=True)

    # 1. Загружаем holdout с таргетами
    holdout_df = pd.read_csv(ARGS.holdout_csv)
    if ARGS.target_col not in holdout_df.columns:
        raise ValueError(f"В {ARGS.holdout_csv} нет колонки '{ARGS.target_col}'")
    y_holdout = holdout_df[ARGS.target_col].astype(int).to_numpy()
    n_holdout = len(y_holdout)
    print(f"[data] holdout: {n_holdout} строк, target rate = {y_holdout.mean():.4f}")

    # 2. Загружаем вероятности базовых моделей на holdout
    bert_holdout = load_probs(ARGS.bert_holdout_probs, n_holdout, "bert-holdout")
    lgb_holdout = load_probs(ARGS.lgb_holdout_probs, n_holdout, "lgb-holdout")

    print(f"[holdout] BERT solo PR-AUC = "
          f"{average_precision_score(y_holdout, bert_holdout):.4f}")
    print(f"[holdout] LGB  solo PR-AUC = "
          f"{average_precision_score(y_holdout, lgb_holdout):.4f}")
    print(f"[holdout] corr(BERT, LGB) = "
          f"{np.corrcoef(bert_holdout, lgb_holdout)[0, 1]:.3f}")

    X_meta = build_meta_features(bert_holdout, lgb_holdout)

    # 3. Обучаем мета-модель
    meta_model, meta_oof = train_meta_model(X_meta, y_holdout)

    # Сохраняем мета-модель
    meta_model_path = os.path.join(ARGS.output_dir, "meta_lgb_model.txt")
    meta_model.booster_.save_model(meta_model_path)
    print(f"[save] мета-модель: {meta_model_path}")

    # Сохраняем OOF-предсказания (пригодятся для анализа)
    oof_path = os.path.join(ARGS.output_dir, "meta_oof_probs.npy")
    np.save(oof_path, meta_oof)

    # Сохраняем конфиг запуска
    config_path = os.path.join(ARGS.output_dir, "meta_config.json")
    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(vars(ARGS), f, ensure_ascii=False, indent=2)

    # 4. Применяем мета-модель к тесту
    test_df = pd.read_csv(ARGS.test_csv)
    n_test = len(test_df)

    bert_test = load_probs(ARGS.bert_test_probs, n_test, "bert-test")
    lgb_test = load_probs(ARGS.lgb_test_probs, n_test, "lgb-test")

    X_test_meta = build_meta_features(bert_test, lgb_test)
    final_probs = meta_model.predict_proba(X_test_meta)[:, 1]

    # 5. Формируем submission
    if "row_id" in test_df.columns:
        row_id = test_df["row_id"]
    elif "Unnamed: 0" in test_df.columns:
        row_id = test_df["Unnamed: 0"]
    else:
        row_id = np.arange(n_test)

    submission = pd.DataFrame({"row_id": row_id, "target": final_probs})
    submission_path = os.path.join(ARGS.output_dir, "submission.csv")
    submission.to_csv(submission_path, index=False)

    # Также сохраним «сырые» тестовые вероятности (для последующего анализа/ансамблей)
    np.save(os.path.join(ARGS.output_dir, "test_meta_probs.npy"), final_probs)

    print("\n[done] Submission preview:")
    print(submission.head())
    print(f"[done] submission: {submission_path}")
    print(f"[done] test probs: {os.path.join(ARGS.output_dir, 'test_meta_probs.npy')}")


if __name__ == "__main__":
    main()
